### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by nicks101** [infiniteoverflow/Libro#30]
Proposal to add following Github Actions to save time on reviewing pull requests and automate apk/ipa generation.

- [x] `Analyze dart and flutter` on the following platform -> Windows, Linux, Mac (more can be added).
- [x] Run flutter `unit test` (if any)
- [ ] Run flutter `integration test` (if any)
- [ ] Generate `apk` and `ipa` Further, release them to `firebase app distribution` (will have to check if possible).

First, second, and third can be applied for event `pull_request`.
Fourth can be applied for event `push on master branch`.

Further Github Actions can also be added

- Adding label(s) like `under_review` on PR
- [spell check](https://github.com/marketplace/actions/simple-cspell)

**Comment by infiniteoverflow** [comment]
Yes , you can go ahead with these actions. Try implementing the `under_review` and `review_requested` label as well. And regarding the spell check , lets skip that for now. Because spell-check might annotate for weird but acceptable variable names too. So leaving that for now , you can integrate the other actions.

**Comment by nicks101** [comment]
Github Actions that are done : 

- [x] Add label `under_review` and `review_requested` when PR is opened.
- [x] Analyze and run test (unit) on ubuntu, windows, and macOS.
- [x] Build apk and ipa and upload to artifacts.

Above jobs run on `pull_request events`.

Github Action to implement 
- [ ] upload apk and ipa to firebase distribution.

For the above job, what should be the event?
Also, before uploading to firebase distribution, we should increment the build(version) number so while downloading it, the app doesn't downgrade.

**Comment by infiniteoverflow** [comment]
Lets do one thing now , we can use a push event for building the apk. The firebase part let's skip it for now, because we would need the Storage for other purposes of the app, and our apk and ipa will cost around 150MB collectively. Firebase Spark Plan has certain storage limitations.

So , just build an apk everytime a push event occurs.

**Comment by nicks101** [comment]
1. push on `main` branch yes?

2. Also, correct me if I'm wrong but using `firebase app distribution` is free doesn't add any storage. 
Reference
- [firebase pricing](https://firebase.google.com/pricing)

**Comment by infiniteoverflow** [comment]
1. Yes , main branch

2. Oh yes,sorry i kind of missed out on that part.  So you may be able to build the apk only as IPA files require certificates, which currently i dont have. So you go ahead.

**Comment by infiniteoverflow** [comment]
@nicks101 Just let me know if you have access to the Firebase project or not.

**Comment by nicks101** [comment]
I don't have access. Direct messaged my email to you.

**Comment by nicks101** [comment]
Hey @infiniteoverflow, after taking pull the latest `main` branch I got several errors and can't run the app :

- `pubspec.yaml` has duplicate dependencies
- `.flutter-plugins-dependencies` is not supposed to be in git, yet it was modified.
- `analysis_options.yaml` was deleted.
