### ISSUE TITLE
Add book list to this app

### ISSUE THREAD

**Issue by SamarpanCoder2002** [infiniteoverflow/Libro#38]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Authentication almost completed but not additional things..... I want to add a book list in this application to go forward in new steps

**Describe alternatives you've considered**
I want to add Book List to this app.... For that what you should prefer?? May I use any API to fetch many book details to store in a list or Manually add book names in that application.....
1. For fetch from any API, can you suggest to me about any API ?.... and to store book name and other details I need to access cloud firestore.........
2. If I manually add book name and store in Cloud Firestore, I also need to access cloud firestore to store data.... 

**Additional context**
If I can forward with that, Please assign me to here(I am also a gssoc'21 participant) and give me firebase account access(my gmail: samarpanofficial2021@gmail.com) and also cloud firestore access to store data....
Please specify one of two points to apply it..... Thank you @infiniteoverflow

**Comment by infiniteoverflow** [comment]
Appreciate your enthusiasm @SamarpanCoder2002 , we are planning to add the books in RealTime Database for now by creating a section for books.
You can help us in adding more books manually, because we are not planning to use any APIs. But i am afraid you wont be able to get any points for that as it is to be done on the firebase console. If thats okay with you , kindly message in the Discord channel and we will share the details.

Sorry , but i may have to close this issue for now.
