### ISSUE TITLE
Add Double-back Exit on Homepage

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Libro#76]
We need to override the back button and implement the "Double-back to Exit" feature. 

You can use this package : https://pub.dev/packages/double_back_to_close_app

**Comment by D-Ajay-Kumar** [comment]
Can do it.

**Comment by anotherwebguy** [comment]
> We need to override the back button and implement the "Double-back to Exit" feature.
> 
> You can use this package : https://pub.dev/packages/double_back_to_close_app

I can work on this issue @infiniteoverflow

**Comment by infiniteoverflow** [comment]
I am sorry @anotherwebguy , Since @D-Ajay-Kumar has commented on this issue first , it will be assigned to him. Do look out for more issues or feel free to raise an issue of your own.

**Comment by D-Ajay-Kumar** [comment]
On it

**Comment by D-Ajay-Kumar** [comment]
The double back exit is working but it's taking user to the login screen again where there's an alert dialog that says "Login complete enjoy the app". Should it be like that? This alert dialog seems kinda useless coz why would anyone want to see a dialog box after logging in to confirm the login has been successful, not to mention it doesn't occur after logging in, only when double back is pressed on home screen.

**Comment by D-Ajay-Kumar** [comment]
And this is happening coz after logging in there is a navigator that pushes the home screen on top of the login screen because of which the user can press the back button and go to this login screen again without pressing the logout button. There should instead be a push replacement so that the back button closes the app. And when the logout button is pressed, this home screen should be replaced with the login screen again.

**Comment by infiniteoverflow** [comment]
@D-Ajay-Kumar use `SystemNavigator.pop()` to close the app. Dont perform navigation to the login screen. That is something that we dont need in the app.
Once a person double clicks back button , the app should close.

**Comment by D-Ajay-Kumar** [comment]
Done. Please check the code :)
