### ISSUE TITLE
Adding profiles for donors and receivers

### ISSUE THREAD

**Issue by vinc3nati** [infiniteoverflow/Libro#8]
We can add a profile section for both and show them how many books they took or donated.

**Comment by infiniteoverflow** [comment]
Yes we can , thats a good idea. But in order to implement that , we may have to setup other features first , we cant start with this directly.

You can work on this once the dashboard and user profiles are created.

**Comment by abhishek7997** [comment]
I can work on this
Please assign this to me.

**Comment by infiniteoverflow** [comment]
I am sorry @abhishek7997 , since @vinc3nati is the author of this issue. It will be assigned to him. But dont worry you can look out for more issues which will be posted soon enough.

**Comment by infiniteoverflow** [comment]
@vinc3nati This issue will be closed for now. You can create a new issue later for showing the books put up for sale by a particular user. This is because, we are not facilitating any payments on our app. The app functions just as a platform for connecting people.
Reach out to me or the mentors for any queries.
