### ISSUE TITLE
Authentication Password

### ISSUE THREAD

**Issue by suraj0223** [infiniteoverflow/Libro#81]
**Some Strict rules can be defined while creating a while SignUp**

A generalized password must be _6 characters long_, should contain a _numeric character_, should contain an _UpperCase character_, should contain a special symbol from **[ !, @,#,$,%,^,&,*]**. 

**Solution**
This can be easily improved by using a strong validator while signup in the password validator section.

**Comment by suraj0223** [comment]
@infiniteoverflow I would like to improve this feature in the application, so that Users can signup with a strong password.

**Comment by infiniteoverflow** [comment]
@suraj0223 Thanks for creating this issue. But since we are using Firebase Authentication for Signing the user , it already provides Validation from Firebase.

You can do one thing. Firebase returns an exception when the password doesn't meet its criteria, so u can try to validate those exceptions and show a snackbar or something to denote an error.

Can you work on that ?

**Comment by suraj0223** [comment]
yeah, sure I will work on that.  I will do my research on exceptions returned by firebase. If you find any resource related to the same kindly share.

**Comment by infiniteoverflow** [comment]
Actually there might be only one exception returned for password... You can check that by going to the sign up screen , enter a very small password and check its output on the console.
